### ISSUE TITLE
Can parse *.tflite file directly?

### ISSUE THREAD

**Issue by leaf918** [jackwish/tflite#1]
if there is a demo will be friendly.

**Comment by zhenhuaw-me** [comment]
Hi @leaf918 , yes, this package can parse `*.tflite` directly. https://github.com/jackwish/tflite/blob/master/tests/test_easy_import.py is a very simple example of load the model. Will add more examples later on :)

**Comment by zhenhuaw-me** [comment]
A mobilenet example can be found at https://github.com/jackwish/tflite/blob/master/tests/mobilenet_example.py
