### ISSUE TITLE
Is it possible to modify the graph and save as new tflite file

### ISSUE THREAD

**Issue by sjzhuo** [jackwish/tflite#2]
Thanks for providing the convince to tool. It would be helpful if graph modification apis can be provided.

**Comment by sjzhuo** [comment]
Thanks for providing the convince to tool. It would be helpful if graph modification apis can be provided.

**Comment by zhenhuaw-me** [comment]
Thanks for your interest. I am sorry that it won't be the part of the project, which aims only to parse flatbuffers files.

Off this project, I guess that it could be better to manipulate the graph in a *training* framework rather than an *inference* engine.
