### ISSUE TITLE
API break (BuiltinCode) due to TensorFlow 2.4.0 change

### ISSUE THREAD

**Issue by zhenhuaw-me** [jackwish/tflite#9]
Starting from [TensorFlow 2.4.0](https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/lite/schema/schema.fbs#L220), the `BuiltinOperator` switches to `int32` from `byte`. As a result, the `OperatorCode.builtin_code` is now an `int32` too, and code like `op_code.BuiltinCode()` is broken. 

```
// An OperatorCode can be an enum value (BuiltinOperator) if the operator is a
// builtin, or a string if the operator is custom.
table OperatorCode {
  // This field is for backward compatibility. This field will be used when
  // the value of the extended builtin_code field has less than
  // BulitinOperator_PLACEHOLDER_FOR_GREATER_OP_CODES.
  deprecated_builtin_code:byte;
  custom_code:string;

  // The version of the operator. The version need to be bumped whenever new
  // parameters are introduced into an op.
  version:int = 1;

  // This field is introduced for resolving op builtin code shortage problem
  // (the original BuiltinOperator enum field was represented as a byte).
  // This field will be used when the value of the extended builtin_code field
  // has greater than BulitinOperator_PLACEHOLDER_FOR_GREATER_OP_CODES.
  builtin_code:BuiltinOperator;
}
``` 

For any code that uses `op_code.BuiltinCode()`, a workaround like the below is needed.

```py

if op_code.BuiltinCode() < BuiltinOperator.PLACEHOLDER_FOR_GREATER_OP_CODES:
    opc = op_code.DeprecatedBuiltinCode()
else:
    opc = op_code.BuiltinCode()
```

**Comment by zhenhuaw-me** [comment]
This blocks `tflite 2.4.0` release - the CI is failing and any package that depends on `tflite` will be down.

**Comment by zhenhuaw-me** [comment]
One way to workaround this is hacking the `OperatorCode` class. But we may not do that unless we have no choice.

**Comment by jackwish** [comment]
One way to workaround this is hacking the `OperatorCode` class. But we may not do that unless we have no choice.
